// src/routes/chat.routes.js
import express from "express";
import { verifyToken } from "../middleware/auth.middleware.js";
import { logger } from "../utils/logger.js";

const router = express.Router();

const SYSTEM_PROMPT = `You are a helpful assistant for Route Pool, a last-mile delivery logistics app used in Nigeria.

Route Pool connects retailers (shops/businesses) with riders (delivery drivers) to fulfil local deliveries efficiently.

KEY FEATURES:
- Retailers create deliveries with customer name, phone, address and package description
- The system automatically geocodes addresses and clusters nearby deliveries into batches
- Riders are assigned batches and pick up from the retailer's shop before delivering to customers
- Deliveries go through statuses: pending → in transit → delivered
- Batches go through: created → in transit → completed
- Verification codes are generated by retailers and entered by riders to confirm delivery at the customer's door
- Riders can view their delivery route on a map with all stops
- Retailers can rate riders after delivery is complete
- Both retailers and riders have a settings page to update their profiles

RETAILER FLOW:
1. Sign up with shop name, shop address and phone
2. Create deliveries with customer details
3. Deliveries get geocoded and auto-batched with nearby deliveries
4. Generate a verification code when the rider reaches the customer
5. Rate the rider after completion

RIDER FLOW:
1. Sign up with vehicle type (motorcycle, bicycle, car)
2. View assigned batches on the dashboard
3. Start a batch, pick up orders from the retailer's shop
4. Mark each delivery in transit, then enter the verification code at the customer door
5. Complete the batch when all deliveries are done

Be concise, friendly and practical. Answer app usage questions and general delivery/logistics questions. Never make up features that don't exist. Keep responses short and clear.`;

// POST /api/chat
router.post("/", verifyToken, async (req, res) => {
  try {
    const { messages, userType } = req.body;

    if (!messages || !Array.isArray(messages) || messages.length === 0) {
      return res
        .status(400)
        .json({ success: false, error: "messages array is required" });
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return res
        .status(500)
        .json({ success: false, error: "Gemini API key not configured" });
    }

    // Build Gemini contents array — alternating user/model roles
    const contents = messages.map((m) => ({
      role: m.role === "assistant" ? "model" : "user",
      parts: [{ text: m.content }],
    }));

    const systemInstruction =
      SYSTEM_PROMPT +
      (userType ? `\n\nThe current user is a ${userType}.` : "");

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          system_instruction: { parts: [{ text: systemInstruction }] },
          contents,
          generationConfig: { maxOutputTokens: 500, temperature: 0.7 },
        }),
      },
    );

    if (!response.ok) {
      const err = await response.json();
      logger.error("Gemini API error", { status: response.status, err });
      return res.status(502).json({
        success: false,
        error: "AI service error",
        message: err.error?.message || "Unknown error",
      });
    }

    const data = await response.json();
    const reply = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!reply) {
      return res
        .status(502)
        .json({ success: false, error: "Empty response from AI" });
    }

    return res.status(200).json({ success: true, reply });
  } catch (error) {
    logger.error("Chat route error", { error: error.message });
    res.status(500).json({ success: false, error: "Internal server error" });
  }
});

export default router;
